title: Blog | Naman Kumar
description: Hi, I'm Naman Kumar. Tech Enthusiastic. Growing Programmer & Web Developer.

url: http://namankumar.me/blog/
source: /blog
baseurl: "/blog/"
BASE_PATH : http://namankumar.me/blog
paginate_path: "page:num/"
permalink: :title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: http://namankumar.me
 - title: Blog
   url: http://namankumar.me/blog/
 - title: About
   url: http://namankumar.me/#about
 - title: Resume
   url: http://namankumar.me/#resume
 - title: Portfolio
   url: http://namankumar.me/#portfolio
 - title: Contact
   url: http://namankumar.me/#contact

social:
   github: hereisnaman
   twitter: hereisnaman
   facebook: hereisnaman
   email: naman@outlook.in

google_analytics: "UA-58263416-1"
